openapi: 3.0.0
info:
  version: 1.0.0
  title: Fusion
  contact:
    email: tadeas@runonflux.io
    url: 'https://docs.fusion.runonflux.io'
  license:
    name: UNLICENSED
  description: 'This is an API documentation for Fusion mainly used in zelcore. Calls can additionally provide zelid header where zelid is zelcores ZelID or any bitcoin user address. Currently supported chains are: Main chain, Ethereum (ETH) chain, Binance Smart Chain (BSC) chain and Kadena (KDA) chain where fusion operates on chain ID 0.'
externalDocs:
  description: Fusion
  url: 'https://github.com/zelcore-io/fusion'
tags:
  - name: general
    description: Calls that are used for overall information about Fusion
  - name: snapshots
    description: Calls for interacting with Fusion snapshots and snapshot claming
  - name: coinbase
    description: Calls for interacting with Flux coinbase and Fusion coinbase claiming (mining rewards)
  - name: swap
    description: Interaction with Swapping Flux between its chains using Fusion
servers:
  - url: 'https://fusion.runonflux.io'
  - url: 'https://testfusion.runonflux.io'
paths:
  /fees:
    get:
      tags:
        - general
      summary: Fees tied with using Fusion services
      description: 'Apart from its main chain, Flux is present also as a token on multiple other chains. Doing on chain transactions comes with a cost of using gas - native coin on those chains. Fusion is charging those fees from end user to remain sustainable in the form of sending less Flux than is user allowance. Each section has its flat fee, additionally a percentage fee may be applied.'
      operationId: fusionfees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Fees information for Fusion services
                    properties:
                      snapshot:
                        type: object
                        description: Fees tied with claiming snapshot
                        properties:
                          percentage:
                            type: number
                            description: 'Percentage fee from amount. Percentage fee is in absolute value. To get the percentage fee substracted, multiply percentage with user amount and round up to higher value.'
                          kda:
                            type: number
                            description: Flat Flux-KDA fee for claiming snapshot on KDA chain. User will receive this amount of Flux-KDA less.
                          eth:
                            type: number
                            description: Flat Flux-ETH fee for claiming snapshot on ETH chain. User will receive this amount of Flux-ETH less.
                          bsc:
                            type: number
                            description: Flat Flux-BSC fee for claiming snapshot on BSC chain. User will receive this amount of Flux-BSC less.
                      mining:
                        type: object
                        description: 'Percentage fee from amount. Percentage fee is in absolute value. To get the percentage fee substracted, multiply percentage with user amount and round up to higher value.'
                        properties:
                          percentage:
                            type: number
                            description: Percentage fee from amount. Users claimable amount will firstly be substracted of this amount of percent. Rounded to higher amount.
                          kda:
                            type: number
                            description: Flat Flux-KDA fee for claiming coinbase on KDA chain. User will receive this amount of Flux-KDA less.
                          eth:
                            type: number
                            description: Flat Flux-ETH fee for claiming coinbase on ETH chain. User will receive this amount of Flux-ETH less.
                          bsc:
                            type: number
                            description: Flat Flux-BSC fee for claiming coinbase on BSC chain. User will receive this amount of Flux-BSC less.
                      swap:
                        type: object
                        description: 'Fees tied with swapping Flux between chains. Receiving (TO) asset is  substracted for the amount. In case of swap from BSC chain to ETH chain, use eth fee as Fusion is sending Flux-ETH and pays Ethereum network fee which is beared by end user by sending less Flux.'
                        properties:
                          percentage:
                            type: number
                            description: 'Percentage fee from amount. Percentage fee is in absolute value. To get the percentage fee substracted, multiply percentage with user  sent amount and round up to higher value.'
                          kda:
                            type: number
                            description: Flat Flux-KDA fee for swapping to KDA chain. User will receive this amount of Flux-KDA less.
                          eth:
                            type: number
                            description: Flat Flux-ETH fee for swapping to ETH chain. User will receive this amount of Flux-ETH less.
                          bsc:
                            type: number
                            description: Flat Flux-BSC fee for swapping to BSC chain. User will receive this amount of Flux-BSC less.
                          main:
                            type: number
                            description: Flat Flux fee for swapping to Main chain. User will receive this amount of Flux less.
              example:
                status: success
                data:
                  snapshot:
                    percentage: 0
                    kda: 5
                    bsc: 11
                    eth: 141
                  mining:
                    percentage: 0
                    kda: 5
                    bsc: 11
                    eth: 141
                  swap:
                    percentage: 0.001
                    main: 5
                    kda: 5
                    bsc: 11
                    eth: 154
  /messagephrase:
    get:
      tags:
        - general
      summary: Obtain message phrase for authentication purposes
      description: Message phrase is used for authentication purposes. This phrase is used for verifying ownership of an address. Useful for coinbase and snapshot claiming. Phrase is valid for 15 minutes and can only be used once.
      operationId: messagephrase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: string
                    description: A message phrase that shall be signed by claiming address
              example:
                status: success
                data: 1630312899557vx5gmvwvc7d94fz12rhilfzvpgebicf6oatkf8c5paos
  /coinbase/stats:
    get:
      tags:
        - coinbase
      summary: Statistics about coinbase and claiming process
      description: Coinbase claiming is possible since Flux fork on 27th March 2021. From blockheight 825001 all receivers of newly minted coins are eligible for additional 10% of mined coins on other parallel chains even if they have not launched yet.
      operationId: coinbasestats
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Coinbase general information statistics
                    properties:
                      total:
                        type: number
                        description: 'Total coinbase records present in database. A block usually has a reward for mining pool, cumulus, nimbus, stratus node rewards. Thus this number is at least 4 times higher than amount of blocks passed since fork.'
                      totalClaimed:
                        type: number
                        description: Amount of successful coinbase claiming records together on all chains
                      totalSatoshis:
                        type: number
                        description: Amount of satoshis (basic unit of Flux. 1 FLUX = 1e8 satoshis) that was present in coinbase transactions
                      totalFunds:
                        type: number
                        description: Amount of Flux that was present in coinbase transactions
                      totalFundsClaimable:
                        type: number
                        description: 'Amount of Flux that is claimable on all chains. Flux has main chain and will have 10 parallel chains.  Each chain is eligible for 10% of coinbase reward, bringing this number to be equal to totalFuns.'
                      totalFundsClaimed:
                        type: number
                        description: Amount of Flux that was already claimed on parallel chains.
                      totalFundsClaimablePerChain:
                        type: number
                        description: Amount of Flux that is claimable on one particular chain. Shall equal to 10% of totalFundsClaimable.
                      totalFeesPaid:
                        type: number
                        description: Claiming coinbase is associated with fees to pay for gas on particular chains. totalFeesPaid is amount of Flux that user indirectly paid for claiming by receiving little less. The fees go to Flux Foundation for Fusion operation.
              example:
                status: success
                data:
                  total: 491906
                  totalClaimed: 1338
                  totalSatoshis: 1837401366485023
                  totalFunds: 18374013.66485023
                  totalFundsClaimable: 18374013.66485023
                  totalFundsClaimed: 308116.25659239
                  totalFundsClaimablePerChain: 1837401.36648502
                  totalFeesPaid: 16628
  /coinbase/summary:
    get:
      tags:
        - coinbase
      summary: Summary of Flux address for coinbase
      description: 'Displays summary of given Flux address of Fusion coinbase statistics. Node operators can claim without a need for whitelist, miners and pools have to be whitelisted first.'
      operationId: coinbasesummaryaddress
      parameters:
        - in: query
          name: address
          required: true
          schema:
            type: string
          description: Flux main chain address
          example: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Summary of coinbase for a given address
                    properties:
                      address:
                        type: string
                        description: Given main chain address
                      satoshis:
                        type: number
                        description: Total received coinbase amount. Mined or node rewards coins on main chain in satoshis
                      amount:
                        type: number
                        description: Total received coinbase amount. Mined or node rewards coins on main chain in Flux units.
                      numberOfTxs:
                        type: number
                        description: Number of coinbase transactions - mined blocks and node rewards blocks.
                      isMiner:
                        type: boolean
                        description: If an address is a miner or a flux node address. Mining addresses have to be whitelisted first before being able to claim rewards. Specially designed for pools that have to show proof of distributing the rewards to actual miners. Node operators can claim without a need for whitelist
                      maxClaimablePerChain:
                        type: number
                        description: Amount of Flux that can be claimed on one particular chain of Flux.
                      maxClaimableTotal:
                        type: number
                        description: Amount of Flux that can be claimed on all currently launched chains.
                      claimedTotal:
                        type: number
                        description: Total claimed Flux on all chains
                      chainStatistics:
                        type: array
                        description: Statistics of each chain for a given address
                        items:
                          type: object
                          properties:
                            chain:
                              type: string
                              description: Chain that object refers to
                            claimedAmount:
                              type: number
                              description: Amount of Flux that was claimed on the chain
                            receivedAmount:
                              type: number
                              description: Amount of Flux that was received on the chain
                            feesPaid:
                              type: number
                              description: Fees that were paid for receiving Flux on the chain
                            possibleToClaim:
                              type: number
                              description: Amount of Flux that can be claimed on the chain now.
              example:
                status: success
                data:
                  address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                  satoshis: 102750000000
                  amount: 1027.5
                  numberOfTxs: 136
                  isMiner: false
                  maxClaimablePerChain: 102.75
                  maxClaimableTotal: 308.25
                  claimedTotal: 199.875
                  chainStatistics:
                    - chain: kda
                      claimedAmount: 99.9375
                      receivedAmount: 94.9375
                      feesPaid: 5
                      possibleToClaim: 2.8125
                    - chain: eth
                      claimedAmount: 0
                      receivedAmount: 0
                      feesPaid: 0
                      possibleToClaim: 102.75
                    - chain: bsc
                      claimedAmount: 99.9375
                      receivedAmount: 88.9375
                      feesPaid: 11
                      possibleToClaim: 2.8125
  /coinbase/records:
    get:
      tags:
        - coinbase
      summary: Statistics and coinbase records
      description: Statistics and recorded coinbase (mining) records for given address
      operationId: coinbaserecordsaddress
      parameters:
        - in: query
          name: address
          required: true
          schema:
            type: string
          description: Flux main chain address
          example: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Statistics and coinbase records
                    properties:
                      address:
                        type: string
                        description: Given main chain address
                      satoshis:
                        type: number
                        description: Total received coinbase amount. Mined or node rewards coins on main chain in satoshis
                      amount:
                        type: number
                        description: Total received coinbase amount. Mined or node rewards coins on main chain in Flux units.
                      numberOfTxs:
                        type: number
                        description: Number of coinbase transactions - mined blocks and node rewards blocks.
                      transactions:
                        type: array
                        description: Coinbase records
                        items:
                          type: object
                          properties:
                            txid:
                              type: string
                              description: Transaction ID of coinbase record
                            vout:
                              type: number
                              description: Vout index of coinbase record
                            height:
                              type: number
                              description: Blockhegith of coinbase record
                            address:
                              type: string
                              description: Address belonging to the coinbase record - given address
                            satoshis:
                              type: number
                              description: Amount of Flux in the given coinbase record
                            scriptPubKey:
                              type: string
                              description: Script Public Key of given coinbase record
                            coinbase:
                              type: boolean
                              description: If given record is a coinbase or not. Shall be true.
              example:
                status: success
                data:
                  address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                  satoshis: 1125000000
                  amount: 11.25
                  numberOfTxs: 2
                  transactions:
                    - txid: 1906965a4a47ece290bed0e54724b39d8d7322bae08fd75341b21decf59bbb84
                      vout: 1
                      height: 858244
                      address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                      satoshis: 562500000
                      scriptPubKey: 76a9146a2adcbb1a1ada8a48bb28eac2dba382424ec78688ac
                      coinbase: true
                    - txid: cfcf9b61a5a6e21ffeb7ddf367947e333a69214e8d807b311a07f6d7cd210d61
                      vout: 1
                      height: 858649
                      address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                      satoshis: 562500000
                      scriptPubKey: 76a9146a2adcbb1a1ada8a48bb28eac2dba382424ec78688ac
                      coinbase: true
  /coinbase/claimed:
    get:
      tags:
        - coinbase
      summary: Claimed records of coinbase
      description: Statistics and claimed records of coinbase (mining) for given address
      operationId: coinbaseclaimedaddresschain
      parameters:
        - in: query
          name: address
          required: true
          schema:
            type: string
          description: Flux main chain address
          example: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
        - in: query
          name: chain
          required: false
          schema:
            type: string
          description: Chain on which to search for claimed records
          example: kda
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Statistics and claimed coinbase records
                    properties:
                      address:
                        type: string
                        description: Given main chain address
                      numberOfTxs:
                        type: number
                        description: Number of coinbase claimed transactions
                      transactions:
                        type: array
                        description: Coinbase records
                        items:
                          type: object
                          properties:
                            address:
                              type: string
                              description: Address belonging to the claimed coinbase record - given address
                            amount:
                              type: number
                              description: Amount of claimed coinbase coins
                            chain:
                              type: string
                              description: Chain on which the amount of coins was claimed
                            txid:
                              type: string
                              description: Transaction ID or Request Key that sent the funds from Fusion to user claimedAddress
                            claimedAddress:
                              type: string
                              description: Address to which coinbase funds were send to
                            message:
                              type: string
                              description: Message phrase that main chain address was signing to proove ownership of the address
                            signature:
                              type: string
                              description: Signature of given message phrase signed by a main chain address
                            fee:
                              type: number
                              description: Fee that user has paid to fasciliate the claiming and transfer. This less coins were sent to claimedAddress.
              example:
                status: success
                data:
                  address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                  numberOfTxs: 2
                  transactions:
                    - address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                      amount: 99.9375
                      chain: kda
                      txid: RWb1-xiMZbDPBYRkLkuWJA6TsfMothG9lCT0Ezra1Rs
                      claimedAddress: f506abce28bb0d7fc622302c6cb4ede27794b01522cb76c142dbc60e5fc135a7
                      message: 1630141798555l513bv6poyrniq1nezo0kruuu7q86sfnq8e4khef9p4s
                      signature: H0GI9COOvVEYiKJjoFY4gSINH1/+p0K5Ma6qMCtCAE78Qp77CcmV5fPsAYSghN3aMCkepXUnmdiRacQq7TUFrNU=
                      fee: 5
                    - address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                      amount: 99.9375
                      chain: bsc
                      txid: '0xdc1ea3f3fb2c788ba88d0b90ff88e613c1ea1fdcd83af53debf41c9b6bb49b69'
                      claimedAddress: '0x316594e7f55865e27a3abc69cddf0b404b34f3b2'
                      message: 1630141888587p0z5ck835iiovp60ij0xg30c0zak6avh2fsp1avytg8
                      signature: INEBIbSd629/rXFy4zC5HQUeNb6eivrGB9XHMNusKoUmNfKioUrun7nwVKA0FcIk0/DK59RVTnXMdJL5amtIK4U=
                      fee: 11
  /coinbase/available:
    post:
      tags:
        - coinbase
      summary: Checks available coinbase for addresses
      description: Gets Fusion coinbase summary for up to 12 addresses
      operationId: coinbaseavailable
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              properties:
                addresses:
                  type: array
                  description: An array of adresses information
                  items:
                    type: object
                    description: Object specifying address and chain - usually main
                    properties:
                      chain:
                        type: string
                        description: Chain on which to look for coinbase summary. Only 'main' is eligible.
                      address:
                        type: string
                        description: Address for which to look for coinbase summary.
            example:
              address: null
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Summary of coinbase for a given array of addresses
                    items:
                      type: object
                      description: Summary of coinbase for a given address
                      properties:
                        address:
                          type: string
                          description: Given main chain address
                        satoshis:
                          type: number
                          description: Total received coinbase amount. Mined or node rewards coins on main chain in satoshis
                        amount:
                          type: number
                          description: Total received coinbase amount. Mined or node rewards coins on main chain in Flux units.
                        numberOfTxs:
                          type: number
                          description: Number of coinbase transactions - mined blocks and node rewards blocks.
                        isMiner:
                          type: boolean
                          description: If an address is a miner or a flux node address. Mining addresses have to be whitelisted first before being able to claim rewards. Specially designed for pools that have to show proof of distributing the rewards to actual miners. Node operators can claim without a need for whitelist
                        maxClaimablePerChain:
                          type: number
                          description: Amount of Flux that can be claimed on one particular chain of Flux.
                        maxClaimableTotal:
                          type: number
                          description: Amount of Flux that can be claimed on all currently launched chains.
                        claimedTotal:
                          type: number
                          description: Total claimed Flux on all chains
                        chainStatistics:
                          type: array
                          description: Statistics of each chain for a given address
                          items:
                            type: object
                            properties:
                              chain:
                                type: string
                                description: Chain that object refers to
                              claimedAmount:
                                type: number
                                description: Amount of Flux that was claimed on the chain
                              receivedAmount:
                                type: number
                                description: Amount of Flux that was received on the chain
                              feesPaid:
                                type: number
                                description: Fees that were paid for receiving Flux on the chain
                              possibleToClaim:
                                type: number
                                description: Amount of Flux that can be claimed on the chain now.
              example:
                status: success
                data:
                  - address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
                    satoshis: 102750000000
                    amount: 1027.5
                    numberOfTxs: 136
                    isMiner: false
                    maxClaimablePerChain: 102.75
                    maxClaimableTotal: 308.25
                    claimedTotal: 199.875
                    chainStatistics:
                      - chain: kda
                        claimedAmount: 99.9375
                        receivedAmount: 94.9375
                        feesPaid: 5
                        possibleToClaim: 2.8125
                      - chain: eth
                        claimedAmount: 0
                        receivedAmount: 0
                        feesPaid: 0
                        possibleToClaim: 102.75
                      - chain: bsc
                        claimedAmount: 99.9375
                        receivedAmount: 88.9375
                        feesPaid: 11
                        possibleToClaim: 2.8125
                  - address: t1J7WrTnM4tWr5mSjxVNECxKrMmQzggNqJy
                    satoshis: 124878326711914
                    amount: 1248783.26711914
                    numberOfTxs: 33933
                    isMiner: true
                    maxClaimablePerChain: 124878.32671191
                    maxClaimableTotal: 374634.98013573
                    claimedTotal: 0
                    chainStatistics:
                      - chain: kda
                        claimedAmount: 0
                        receivedAmount: 0
                        feesPaid: 5
                        possibleToClaim: 124878.32671191
                      - chain: eth
                        claimedAmount: 0
                        receivedAmount: 0
                        feesPaid: 0
                        possibleToClaim: 124878.32671191
                      - chain: bsc
                        claimedAmount: 0
                        receivedAmount: 0
                        feesPaid: 0
                        possibleToClaim: 124878.32671191
  /coinbase/claim:
    post:
      tags:
        - coinbase
      summary: Claim coinbase rewards
      description: Claim coinbase (mining) rewards for a given address on a given chain
      operationId: coinbaseclaim
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              properties:
                chain:
                  type: string
                  description: 'Chain on which to claim rewards. Available options are eth, kda, bsc'
                address:
                  type: string
                  description: Main chain address for which to claim rewards
                claimingAddress:
                  type: string
                  description: Address (account) on the claiming chain to which rewards will be sent.
                message:
                  type: string
                  description: Obtained message phrase that address was signing
                signature:
                  type: string
                  description: Signature of message signed my address.
            example:
              address: t1TYxynkJE12avxWfd46haSrFEXZN8vMKjU
              chain: bsc
              claimingAddress: '0x316594e7f55865e27a3abc69cddf0b404b34f3b2'
              message: 1630141888587p0z5ck835iiovp60ij0xg30c0zak6avh2fsp1avytg8
              signature: INEBIbSd629/rXFy4zC5HQUeNb6eivrGB9XHMNusKoUmNfKioUrun7nwVKA0FcIk0/DK59RVTnXMdJL5amtIK4U=
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: string
                    description: Transaction ID of coinbase claim
              example:
                status: success
                data: '0xdc1ea3f3fb2c788ba88d0b90ff88e613c1ea1fdcd83af53debf41c9b6bb49b69'
  /swap/activechains:
    get:
      tags:
        - swap
      summary: Active chains for Flux Fusion Swap
      description: 'Flux operates on multiple chains and Fusion allows swapping between them. From time to time due to maintenance, some chains may not be available. This call provides all chains of Flux available for swap. Current options: "main" - Flux main chain, "kda" - FLUX-KDA, "eth" - FLUX-ETH, "bsc" - Flux-BSC.'
      operationId: swapactivechains
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: List of available chains
                    items:
                      type: string
                      description: chain identifier
              example:
                status: success
                data:
                  - main
                  - kda
                  - eth
                  - bsc
  /swap/info:
    get:
      tags:
        - swap
      summary: Information about Fusion Swap
      description: 'Call provides all information needed for user to create Fusion swaps. Provides active chains, coins, confirmations, fees, addresses about Fusion swap. This is a prestep before creating reservation or an actual swap'
      operationId: swapinfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Information about Fusion Swap
                    properties:
                      chains:
                        type: array
                        description: List of available chains
                        items:
                          type: string
                          description: chain identifier
                      coins:
                        type: array
                        description: Information about Flux Fusion coins
                        items:
                          type: object
                          properties:
                            coin:
                              type: string
                              description: Zelcore coin identifier
                            chain:
                              type: string
                              description: Chain on which coin operates
                      confirmations:
                        type: array
                        description: 'Necessary amount of blockchain confirmations for swap to begin for given amount or lower amount. If amount is higher than confirmation amount, swap cannot be processed. Do not send higher amounts than maximum!'
                        items:
                          type: object
                          properties:
                            confirmations:
                              type: number
                              description: Required number of confirmations on depositing coin
                            amount:
                              type: number
                              description: Amount per which the required number of confirmations is shown
                      fees:
                        type: object
                        description: Fees information for Fusion services
                        properties:
                          snapshot:
                            type: object
                            description: Fees tied with claiming snapshot
                            properties:
                              percentage:
                                type: number
                                description: 'Percentage fee from amount. Percentage fee is in absolute value. To get the percentage fee substracted, multiply percentage with user amount and round up to higher value.'
                              kda:
                                type: number
                                description: Flat Flux-KDA fee for claiming snapshot on KDA chain. User will receive this amount of Flux-KDA less.
                              eth:
                                type: number
                                description: Flat Flux-ETH fee for claiming snapshot on ETH chain. User will receive this amount of Flux-ETH less.
                              bsc:
                                type: number
                                description: Flat Flux-BSC fee for claiming snapshot on BSC chain. User will receive this amount of Flux-BSC less.
                          mining:
                            type: object
                            description: 'Percentage fee from amount. Percentage fee is in absolute value. To get the percentage fee substracted, multiply percentage with user amount and round up to higher value.'
                            properties:
                              percentage:
                                type: number
                                description: Percentage fee from amount. Users claimable amount will firstly be substracted of this amount of percent. Rounded to higher amount.
                              kda:
                                type: number
                                description: Flat Flux-KDA fee for claiming coinbase on KDA chain. User will receive this amount of Flux-KDA less.
                              eth:
                                type: number
                                description: Flat Flux-ETH fee for claiming coinbase on ETH chain. User will receive this amount of Flux-ETH less.
                              bsc:
                                type: number
                                description: Flat Flux-BSC fee for claiming coinbase on BSC chain. User will receive this amount of Flux-BSC less.
                          swap:
                            type: object
                            description: 'Fees tied with swapping Flux between chains. Receiving (TO) asset is  substracted for the amount. In case of swap from BSC chain to ETH chain, use eth fee as Fusion is sending Flux-ETH and pays Ethereum network fee which is beared by end user by sending less Flux.'
                            properties:
                              percentage:
                                type: number
                                description: 'Percentage fee from amount. Percentage fee is in absolute value. To get the percentage fee substracted, multiply percentage with user  sent amount and round up to higher value.'
                              kda:
                                type: number
                                description: Flat Flux-KDA fee for swapping to KDA chain. User will receive this amount of Flux-KDA less.
                              eth:
                                type: number
                                description: Flat Flux-ETH fee for swapping to ETH chain. User will receive this amount of Flux-ETH less.
                              bsc:
                                type: number
                                description: Flat Flux-BSC fee for swapping to BSC chain. User will receive this amount of Flux-BSC less.
                              main:
                                type: number
                                description: Flat Flux fee for swapping to Main chain. User will receive this amount of Flux less.
                      swapAddresses:
                        type: array
                        description: Deposit Swap Addressses of Fusion. You will be sending your depositing coin to the following address corresponding to your depositing chain
                        items:
                          type: object
                          properties:
                            chain:
                              type: string
                              description: Chain to which Address/Account belongs to
                            address:
                              type: string
                              description: Address/Account to deposit coins to
              example:
                status: success
                data:
                  chains:
                    - main
                    - kda
                    - eth
                    - bsc
                  coins:
                    - coin: zelcash
                      chain: main
                    - coin: fluxkda
                      chain: kda
                    - coin: fluxeth
                      chain: eth
                    - coin: fluxbsc
                      chain: bsc
                  confirmations:
                    - confirmations: 4
                      amount: 5000
                    - confirmations: 7
                      amount: 10000
                    - confirmations: 12
                      amount: 25000
                    - confirmations: 20
                      amount: 50000
                    - confirmations: 30
                      amount: 100000
                  fees:
                    snapshot:
                      percentage: 0
                      kda: 5
                      bsc: 11
                      eth: 141
                    mining:
                      percentage: 0
                      kda: 5
                      bsc: 11
                      eth: 141
                    swap:
                      percentage: 0.001
                      main: 5
                      kda: 5
                      bsc: 11
                      eth: 154
                  swapAddresses:
                    - chain: main
                      address: t1abAp9oZenibGLFuZKyUjmL6FiATTaCYaj
                    - chain: kda
                      address: fluxswap
                    - chain: eth
                      address: '0x134e4c74c670adefdcb2476df6960d9297bc7dad'
                    - chain: bsc
                      address: '0x9b192227da99b5a50d037b10c965609ed83c43d7'
  /swap/detail:
    get:
      tags:
        - swap
      summary: Detail of a Swap
      description: Displays details of supplied swap of Fusion
      operationId: swapdetail
      parameters:
        - in: query
          name: txid
          required: true
          schema:
            type: string
          description: TXID of depositing Fusion Swap transaction
          example: dd22d70eb83c02232de38c2f3daad6d2470334cc4b3ec855fd4d6ac926cbf99b
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Detail of Swap
                    properties:
                      expectedAmountFrom:
                        type: number
                        description: Expected amount that user should deposit
                      expectedAmountTo:
                        type: number
                        description: Expected amount that user will receive calculated as expectedAmountFrom - fee where fee is depending on amount.
                      chainFrom:
                        type: string
                        description: 'Chain on which user will deposit coins to, selling chain'
                      chainTo:
                        type: number
                        description: 'Chain on which user whishes to receive coins, buying chain'
                      addressFrom:
                        type: string
                        description: Users depositing address of chainFrom
                      addressTo:
                        type: string
                        description: Users receiving address on chainTo
                      txidFrom:
                        type: string
                        description: Users depositing transaction ID on chainFrom
                      zelid:
                        type: string
                        description: Users Zelid identifier
                      fee:
                        type: number
                        description: Actual or expected fee. That amount will be sent less than amountFrom as swaps of Flux are always 1 to 1 rate
                      status:
                        $ref: '#/components/schemas/exchangestatus'
                      timestamp:
                        type: number
                        description: Timestamp of when Swap was created
                      confsRequired:
                        type: number
                        description: Confirmations on depositing chain required - depends on amount deposited
                      amountFrom:
                        type: number
                        description: Actual amount deposited on chainFrom
                      amountTo:
                        type: number
                        description: Actual amount sent or that will be sent on chainTo
                      txidTo:
                        type: string
                        description: 'Transaction ID on receiving chainTo chain - TXID that Fusion sent to user, swap was finished.'
              example:
                status: success
                data:
                  expectedAmountFrom: 6.5
                  expectedAmountTo: 2.5
                  chainFrom: main
                  chainTo: kda
                  addressFrom: t1UPSwfMYLe18ezbCqnR5QgdJGznzCUYHkj
                  addressTo: 3a2e6166907d0c2fb28a16cd6966a705de129e8358b9872d9cefe694e910d5b2
                  txidFrom: dd22d70eb83c02232de38c2f3daad6d2470334cc4b3ec855fd4d6ac926cbf99b
                  zelid: 1CbErtneaX2QVyUfwU7JGB7VzvPgrgc3uC
                  fee: 4
                  status: finished
                  timestamp: 1629656716983
                  confsRequired: 3
                  amountFrom: 6.5
                  amountTo: 4.5
                  txidTo: VD2S_KF03zl6oEJHAUf0HYnXaQmTtG_KyxSrHvE-nuM
components:
  schemas:
    signature:
      description: Signature of signed messagePhrase.
      type: string
      example: H+ZB3oSrsw6XkBxxlbwk33LEBJYvqtbMIm2kL9JzuoXMC6pSZd0lBHdnhJYzMTXv81zZQ7G/pkK1NvYN7cNF0GE=
    ErrorMessage:
      type: object
      properties:
        status:
          type: string
          description: error
        data:
          type: object
          properties:
            code:
              type: string
              description: code of error
            name:
              type: string
              description: name of error
            message:
              type: string
              description: message of error
    status:
      type: string
      description: Explanation of status
      enum:
        - success
        - error
    chain:
      type: string
      description: Chain of particular asset to further identify where an asset exists
      enum:
        - main
        - eth
        - bsc
        - kda
    exchangestatus:
      type: string
      description: 'Status of an exchange. New - for new exchange. Waiting - awaiting deposit of funds.  Confirming - picking confirmations on deposit of funds. Exchanging - funds are being exchanged and buy coin is sending. Finished - exchange is comepleted. Expired - Funds were not received in time.  Hold - ecxhange is holding the funds mostly due to KYC reasons. Dust - received amount is below fusion fees. Swap is finished, 0 assets sent.'
      enum:
        - new
        - waiting
        - confirming
        - exchanging
        - finished
        - hold
        - expired
        - dust
  headers:
    zelid:
      description: ZelID header
      schema:
        type: string
